### PR TITLE
Add workflow for building test across plantforms & pytorch & CUDA

### PR DESCRIPTION
**Pull request by liruilong940607**

### CODE REVIEW

**Review by vye16 — APPROVED** [review]
Looks great! Thanks!

**Comment by liruilong940607** [comment]
Could you merge? I don't have the permission to merge lol

**Comment by vye16** [comment]
Oh okay I'll merge and I think I can make you an admin

**Comment by vye16** [comment]
Ah, actually it seems to be out of date with main, could you resolve conflicts?

**Pull request merged**
