### PR TITLE
Eval table

### PR DESCRIPTION
**Pull request by AdamRashid96**
Added eval table to the docs.

Screenshot 2024-02-22 at 3 01 03 PM

### CODE REVIEW

**Review by vye16 — APPROVED** [review]
lgtm!

**Comment by jb-ye** [comment]
Could you describe how do you process the images to generate the undistorted images and colmap project? Are you using Inria's [convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py)? @AdamRashid96

**Comment by AdamRashid96** [comment]
> Could you describe how do you process the images to generate the undistorted images and colmap project? Are you using Inria's [convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py)? @AdamRashid96

I ran Inria's [convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py) for the Mipnerf-360 dataset, and then I generated a transforms.json file with the nerfstudio formatting, so I could train nerfstudio's splatfacto with the same poses and colmap parameters.

**Comment by jb-ye** [comment]
@AdamRashid96 When you convert data to nerfstudio format, did you use the undistorted or distorted colmap cameras?

**Comment by jb-ye** [comment]
I strongly recommend to re-run splatfacto's evaluation using colmap parser after this fix: https://github.com/nerfstudio-project/gsplat/pull/136 properly integrated.

**Comment by ichsan2895** [comment]
> > Could you describe how do you process the images to generate the undistorted images and colmap project? Are you using Inria's [convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py)? @AdamRashid96
> 
> I ran Inria's [convert.py](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/convert.py) for the Mipnerf-360 dataset, and then I generated a transforms.json file with the nerfstudio formatting, so I could train nerfstudio's splatfacto with the same poses and colmap parameters.

Why you choose python3 convert.py instead of nerfstudio-dataparser.

FYI I have implement `ns-process-data splatfacto` in my own repo `ichsan2895/nerfstudio`. It mimics `python convert.py` but it compatibles with `nerfstudio-dataparser` because it creates `sparse_pc.ply` and `transform.json.`

**Pull request merged**
