### PR TITLE
[Docs] Evaluation metrics for mcmc, antialiased, and absgrad.

### PR DESCRIPTION
**Pull request by maturk**
|                             | PSNR  | SSIM  | LPIPS | Num GSs  | Mem (GB)| Time (min) |
|-----------------------------|-------|-------|-------|----------|---------|------------|
| gsplat (default settings)   | 29.00 | 0.87  | 0.14  | 3237318  | 5.62    | 19.39      |
| absgrad                     | 29.11 | 0.88  | 0.12  | 2465986  | 4.40    | 18.10      |
| antialiased                 | 29.03 | 0.87  | 0.14  | 3377807  | 5.87    | 19.52      |
| mcmc  (1 mill)              | 29.18 | 0.87  | 0.14  | 1000000  | 1.98    | 15.42      |
| mcmc  (2 mill)              | 29.53 | 0.88  | 0.13  | 2000000  | 3.43    | 21.79      |
| mcmc  (3 mill)              | 29.65 | 0.89  | 0.12  | 3000000  | 4.99    | 27.63      |
| absgrad & antialiased       | 29.14 | 0.88  | 0.13  | 2563156  | 4.57    | 18.43      |
| mcmc & antialiased          | 29.23 | 0.87  | 0.14  | 1000000  | 2.00    | 15.75      |

Averaged over 7 scenes from MiP-NeRF 360 with an A100 GPU. absgrad method uses `--grow_grad2d 0.0006`

### CODE REVIEW

**Comment by jb-ye** [comment]
nice work!

**Comment by kerrj** [comment]
Very cool! For each did you use the `simple_trainer*.py` script?

**Comment by maturk** [comment]
> Very cool! For each did you use the `simple_trainer*.py` script?

Yes exactly! simple_trainer.py for gsplat/absgrad/antialiased and simple_trainer_mcmc.py for mcmc/mcmc+antialiased. Let me know if there are any other interesting experiments I missed.

**Comment by ichsan2895** [comment]
I have done some experiment in nerfstudio discord channel. Feel free to use my render video & metrics from my experiment.

**Review by jb-ye — APPROVED** [review]
LGTM!

**Pull request merged**
